### ISSUE TITLE
Keep app running?

### ISSUE THREAD

**Issue by Bluscream** [Spksh/TentacleSoftware.TeamSpeakQuery#12]
How can i make the bot stay online? I even tried console.readkey()
https://github.com/Bluscream/ServerQuery-TS3Dump/blob/master/TS3Dump/Program.cs#L21

```
connected True
login True 0 ok
use True 0 ok
registered for ConnectionClosed
registered for NotifyClientEnterView
```

**Comment by Spksh** [comment]
Can you give me some more information on the problem, please? Are you receiving an error message?

**Comment by Bluscream** [comment]
No but the bot is connecting and instantly disconnecting

**Comment by Spksh** [comment]
I've just run your sample code against a known-good TS3 server, and I don't see an instant disconnect; it appears to work fine. 

Can you explain in more detail what you're seeing, please?

**Comment by Bluscream** [comment]
Damm, i just turned off my pc. Gonna record a video tomorrow (12:38am here)

**Comment by Spksh** [comment]
Closing. If you're still having problems, please reopen.
