### ISSUE TITLE
Undocumented -ip option missing in Option enum

### ISSUE THREAD

**Issue by cralexns** [Spksh/TentacleSoftware.TeamSpeakQuery#8]
The documentation doesn't mention the -ip option but it's used on the clientlist command to include client IP addresses.

It may be beneficial to include the ability to define additional options.

**Comment by Spksh** [comment]
Added -ip in 7dcf8a9dc9fe0c0e1db6d9828d5ef7d09bbbb99f, let me know if that works for you. 

If you need arbitrary parameters and options, you can write extended versions of ResultFactory.ToCommandString and ServerQueryCommand. Wouldn't be too hard to add an arbitrary stringifier.

**Comment by cralexns** [comment]
It should work, did the same in my fork. :)

**Comment by Spksh** [comment]
Cool. If you make another fix like this, definitely submit a pull request :)
